spring:
  application:
    name: blog-application-api

  # DATASOURCE CONFIGURATION

  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/blog_api_db?createDatabaseIfNotExist=true}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


app:
  client:
    origin: ${CLIENT_ORIGIN:http://localhost:5175}
